//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMEAD.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles_Applications
    {
        public System.Guid RoleId { get; set; }
        public System.Guid ApplicationId { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual aspnet_Applications aspnet_Applications { get; set; }
        public virtual aspnet_Roles aspnet_Roles { get; set; }
    }
}
